import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Cards from '../components/cards'

const Movies: NextPage = () => {

    return (
      <div className={styles.container}>
        <Head>
          <title>Movies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar name="Movies"/>
        <Cards progType="movie" indexNum={55}/>
        <Footer/>
  
      </div>
    )
}

export default Movies