import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Cards from '../components/cards'

const Series: NextPage = () => {
    return (
      <div className={styles.container}>
        <Head>
          <title>Series</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar name="Series"/>
        <Cards progType="series" indexNum={25}/>
        <Footer/>

      </div>
    )
}

export default Series